In [151]:
#Importing Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import os
import sklearn
from sklearn.preprocessing import StandardScaler

## Importing Dataframe

In [152]:
path= r'C:\Users\solom\Downloads\Machine Learning- Project'

In [153]:
df = pd.read_csv(os.path.join(path, 'Original Data', 'Dataset-weather-prediction-dataset-processed.csv'))

In [154]:
df.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [155]:
#Indexing and creating a new column named ID
df.reset_index(inplace=True)
df.rename(columns={'index':'ID'}, inplace=True)
df.head()

,ID,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22950 entries, 0 to 22949
Columns: 171 entries, ID to VALENTIA_temp_max
dtypes: float64(145), int64(26)
memory usage: 29.9 MB

## Check for missing values

In [157]:
df.isnull().sum()

ID                     0
DATE                   0
MONTH                  0
BASEL_cloud_cover      0
BASEL_wind_speed       0
                      ..
VALENTIA_snow_depth    0
VALENTIA_sunshine      0
VALENTIA_temp_mean     0
VALENTIA_temp_min      0
VALENTIA_temp_max      0
Length: 171, dtype: int64

In [158]:
# Drop the NaN values

df.dropna(inplace=True)

### No missing values found

In [159]:
df.shape

(22950, 171)

## Scaling Data

In [160]:
#create scaler object using StandardScaler from sklearn.preprocessing
#StandardScaler assumes data is normally distributed and scales with a distribution
#around 0 and standard deviation of 1. Scaling happens independently with each variable.

scaler = StandardScaler()

In [161]:
df.columns

Index(['ID', 'DATE', 'MONTH', 'BASEL_cloud_cover', 'BASEL_wind_speed',
       'BASEL_humidity', 'BASEL_pressure', 'BASEL_global_radiation',
       'BASEL_precipitation', 'BASEL_snow_depth',
       ...
       'VALENTIA_cloud_cover', 'VALENTIA_humidity', 'VALENTIA_pressure',
       'VALENTIA_global_radiation', 'VALENTIA_precipitation',
       'VALENTIA_snow_depth', 'VALENTIA_sunshine', 'VALENTIA_temp_mean',
       'VALENTIA_temp_min', 'VALENTIA_temp_max'],
      dtype='object', length=171)

In [162]:
#columns to scale
columns_to_scale= ['BASEL_cloud_cover',	'BASEL_wind_speed',	'BASEL_humidity',	'BASEL_pressure',	'BASEL_global_radiation',	'BASEL_precipitation',	'BASEL_snow_depth',	'BASEL_sunshine',	'BASEL_temp_mean',	'BASEL_temp_min',	'BASEL_temp_max',	'BELGRADE_cloud_cover',	'BELGRADE_humidity',	'BELGRADE_pressure',	'BELGRADE_global_radiation',	'BELGRADE_precipitation',	'BELGRADE_sunshine',	'BELGRADE_temp_mean',	'BELGRADE_temp_min',	'BELGRADE_temp_max',	'BUDAPEST_cloud_cover',	'BUDAPEST_humidity',	'BUDAPEST_pressure',	'BUDAPEST_global_radiation',	'BUDAPEST_precipitation',	'BUDAPEST_sunshine',	'BUDAPEST_temp_mean',	'BUDAPEST_temp_min',	'BUDAPEST_temp_max',	'DEBILT_cloud_cover',	'DEBILT_wind_speed',	'DEBILT_humidity',	'DEBILT_pressure',	'DEBILT_global_radiation',	'DEBILT_precipitation',	'DEBILT_sunshine',	'DEBILT_temp_mean',	'DEBILT_temp_min',	'DEBILT_temp_max',	'DUSSELDORF_cloud_cover',	'DUSSELDORF_wind_speed',	'DUSSELDORF_humidity',	'DUSSELDORF_pressure',	'DUSSELDORF_global_radiation',	'DUSSELDORF_precipitation',	'DUSSELDORF_snow_depth',	'DUSSELDORF_sunshine',	'DUSSELDORF_temp_mean',	'DUSSELDORF_temp_min',	'DUSSELDORF_temp_max',	'GDANSK_cloud_cover', 'GDANSK_humidity',	'GDANSK_precipitation',	'GDANSK_snow_depth',	'GDANSK_temp_mean',	'GDANSK_temp_min',	'GDANSK_temp_max',	'HEATHROW_cloud_cover',	'HEATHROW_humidity',	'HEATHROW_pressure',	'HEATHROW_global_radiation',	'HEATHROW_precipitation',	'HEATHROW_snow_depth',	'HEATHROW_sunshine',	'HEATHROW_temp_mean',	'HEATHROW_temp_min',	'HEATHROW_temp_max',	'KASSEL_wind_speed',	'KASSEL_humidity',	'KASSEL_pressure',	'KASSEL_global_radiation',	'KASSEL_precipitation',	'KASSEL_sunshine',	'KASSEL_temp_mean',	'KASSEL_temp_min',	'KASSEL_temp_max',	'LJUBLJANA_cloud_cover',	'LJUBLJANA_wind_speed',	'LJUBLJANA_humidity',	'LJUBLJANA_pressure',	'LJUBLJANA_global_radiation',	'LJUBLJANA_precipitation',	'LJUBLJANA_sunshine',	'LJUBLJANA_temp_mean',	'LJUBLJANA_temp_min',	'LJUBLJANA_temp_max',	'MAASTRICHT_cloud_cover',	'MAASTRICHT_wind_speed',	'MAASTRICHT_humidity',	'MAASTRICHT_pressure',	'MAASTRICHT_global_radiation', 'MAASTRICHT_precipitation',	'MAASTRICHT_sunshine',	'MAASTRICHT_temp_mean',	'MAASTRICHT_temp_min',	'MAASTRICHT_temp_max',	'MADRID_cloud_cover',	'MADRID_wind_speed',	'MADRID_humidity',	'MADRID_pressure',	'MADRID_global_radiation',	'MADRID_precipitation',	'MADRID_sunshine',	'MADRID_temp_mean',	'MADRID_temp_min',	'MADRID_temp_max',	'MUNCHENB_cloud_cover',	'MUNCHENB_humidity',	'MUNCHENB_global_radiation',	'MUNCHENB_precipitation',	'MUNCHENB_snow_depth',	'MUNCHENB_sunshine',	'MUNCHENB_temp_mean',	'MUNCHENB_temp_min',	'MUNCHENB_temp_max',	'OSLO_cloud_cover',	'OSLO_wind_speed',	'OSLO_humidity',	'OSLO_pressure',	'OSLO_global_radiation',	'OSLO_precipitation',	'OSLO_snow_depth',	'OSLO_sunshine',	'OSLO_temp_mean',	'OSLO_temp_min',	'OSLO_temp_max',	'ROMA_cloud_cover',	'ROMA_wind_speed',	'ROMA_humidity',	'ROMA_pressure',	'ROMA_sunshine',	'ROMA_temp_mean',	'SONNBLICK_cloud_cover',	'SONNBLICK_wind_speed',	'SONNBLICK_humidity',	'SONNBLICK_pressure',	'SONNBLICK_global_radiation',	'SONNBLICK_precipitation',	'SONNBLICK_sunshine',	'SONNBLICK_temp_mean',	'SONNBLICK_temp_min',	'SONNBLICK_temp_max',	'STOCKHOLM_cloud_cover',	'STOCKHOLM_pressure',	'STOCKHOLM_global_radiation', 'STOCKHOLM_precipitation',	'STOCKHOLM_sunshine',	'STOCKHOLM_temp_mean',	'STOCKHOLM_temp_min', 'STOCKHOLM_temp_max',	'TOURS_wind_speed',	'TOURS_humidity',	'TOURS_pressure',	'TOURS_global_radiation',	'TOURS_precipitation',	'TOURS_temp_mean',	'TOURS_temp_min',	'TOURS_temp_max',	'VALENTIA_cloud_cover', 'VALENTIA_humidity', 'VALENTIA_pressure',
       'VALENTIA_global_radiation', 'VALENTIA_precipitation',
       'VALENTIA_snow_depth', 'VALENTIA_sunshine', 'VALENTIA_temp_mean',
       'VALENTIA_temp_min', 'VALENTIA_temp_max']

In [163]:
#create new df with scaled data

df_scaled = pd.DataFrame(scaler.fit_transform(df[columns_to_scale]))
scaled_values= df.copy()
scaled_values[columns_to_scale] = df_scaled

In [164]:
scaled_values.head()

,ID,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,0,19600101,1,0.660514,-0.02793,0.826097,-0.001949,-1.101066,-0.265148,-0.179228,...,-0.443701,0.761754,-1.299744,-0.806427,-0.088407,-0.024706,0.372147,-0.668215,-0.519743,-0.752237
1,1,19600102,1,0.244897,-0.02793,0.735760,-0.001949,-1.058108,1.658760,-0.179228,...,0.783085,1.183580,-1.262455,-1.042055,0.503361,-0.024706,-0.829285,-0.548046,-0.629054,-0.407141
2,2,19600103,1,1.076130,-0.02793,1.277781,-0.001949,-1.251420,0.155707,-0.179228,...,0.783085,1.183580,-0.432779,-1.136306,-0.396127,-0.024706,-1.009500,-0.067372,0.054135,-0.177078
3,3,19600104,1,-1.001953,-0.02793,1.458455,-0.001949,-0.821838,-0.445514,-0.179228,...,0.783085,0.480538,0.387574,-1.183432,0.669056,-0.024706,-1.039536,-0.998679,-0.164486,-0.838511
4,4,19600105,1,0.244897,-0.02793,1.729466,-0.001949,-0.746661,-0.164944,-0.179228,...,-1.670486,-0.363113,1.729970,-0.794645,-0.490810,-0.024706,0.672505,-1.509396,-1.339569,-1.471186

In [165]:
# For comparison between Original and scaled data

df.head()

,ID,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

## Exporting Dataframes

In [166]:
# Export dataframe as .pkl
scaled_values.to_pickle(os.path.join(path, 'Manipulated Data', 'Weather_Dataset_Scaled.pkl'))

In [167]:
# Export dataframe as .csv
scaled_values.to_csv(os.path.join(path, 'Manipulated Data', 'Weather_Data_Scaled.csv'))